FROM node:20-alpine AS build

WORKDIR /app
ARG VITE_API_BASE_URL
ARG VITE_API_TIMEOUT_MS=20000
ARG VITE_API_RETRY_COUNT=1
ARG VITE_HOMELABS_WHATSAPP
ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_TIMEOUT_MS=$VITE_API_TIMEOUT_MS
ENV VITE_API_RETRY_COUNT=$VITE_API_RETRY_COUNT
ENV VITE_HOMELABS_WHATSAPP=$VITE_HOMELABS_WHATSAPP
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
